name: Remove old artifacts

on:
  schedule:
    # Every day at 1am
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  remove-old-artifacts:
    permissions: write-all
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@44fc7acaf1b3d0987da0e8d4707a989d80e9554b # v1.4.0
      with:
        age: '1 week' # '<number> <unit>', e.g. 5 days, 2 years, 90 seconds, parsed by Moment.js
